name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    if: github.repository == 'brc-dd/gcmwrap'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - uses: denoland/setup-deno@v2
      - run: deno task build
      - run: cd dist && npm publish
